# Generated by Django 5.1.2 on 2024-10-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='fecha_es',
            new_name='año',
        ),
    ]
